import re


confidence_rating = {
                            'high': 3,
                            'medium': 2,
                            'low' : 1
                            }

confidence = {
                'http' : 'high',
                'https' : 'high',
                'tls' : 'medium',
                'banner' : 'medium',
                }   


common_ports = {
                20:    "FTP-DATA",
                21:    "FTP",
                22:    "SSH",
                23:    "Telnet",
                25:    "SMTP",
                53:    "DNS",
                67:    "DHCP",
                68:    "DHCP",
                69:    "TFTP",
                80:    "HTTP",
                88:    "Kerberos",
                109:   "POP2",
                110:   "POP3",
                111:   "RPCbind",
                113:   "Ident",
                119:   "NNTP",
                123:   "NTP",
                135:   "MSRPC",
                137:   "NetBIOS-NS",
                138:   "NetBIOS-DGM",
                139:   "NetBIOS-SSN",
                143:   "IMAP",
                161:   "SNMP",
                162:   "SNMP-Trap",
                179:   "BGP",
                194:   "IRC",
                389:   "LDAP",
                443:   "HTTPS",
                445:   "SMB",
                465:   "SMTPS",
                514:   "Syslog",
                515:   "LPD/Printer",
                520:   "RIP",
                587:   "SMTP-Submission",
                593:   "MSRPC-over-HTTP",
                631:   "IPP/CUPS",
                636:   "LDAPS",
                873:   "Rsync",
                902:   "VMware-Auth",
                989:   "FTPS-DATA",
                990:   "FTPS",
                993:   "IMAPS",
                995:   "POP3S",
                1080:  "SOCKS",
                1194:  "OpenVPN",
                1433:  "MSSQL",
                1521:  "Oracle-DB",
                1723:  "PPTP",
                1883:  "MQTT",
                2049:  "NFS",
                2181:  "ZooKeeper",
                2375:  "Docker",
                2376:  "Docker-TLS",
                3000:  "Dev-HTTP",       # common for node/react/grafana dev servers
                3128:  "Squid-Proxy",
                3268:  "LDAP-GC",
                3306:  "MySQL",
                3389:  "RDP",
                3690:  "SVN",
                4369:  "Erlang-EPMD",
                4433:  "Alt-HTTPS",
                5000:  "UPnP/Dev-HTTP",  # common for Flask dev servers
                5060:  "SIP",
                5061:  "SIP-TLS",
                5222:  "XMPP",
                5432:  "PostgreSQL",
                5601:  "Kibana",
                5672:  "AMQP/RabbitMQ",
                5900:  "VNC",
                5984:  "CouchDB",
                6379:  "Redis",
                6443:  "Kubernetes-API",
                6667:  "IRC",
                7001:  "WebLogic",
                7077:  "Spark",
                8000:  "Alt-HTTP",
                8008:  "Alt-HTTP",
                8080:  "HTTP-Proxy",
                8081:  "Alt-HTTP",
                8086:  "InfluxDB",
                8443:  "Alt-HTTPS",
                8500:  "Consul",
                8888:  "Alt-HTTP",
                9000:  "PHP-FPM/Dev",
                9042:  "Cassandra",
                9092:  "Kafka",
                9100:  "JetDirect/Printer",
                9200:  "Elasticsearch",
                9300:  "Elasticsearch-Transport",
                11211: "Memcached",
                15672: "RabbitMQ-Mgmt",
                27017: "MongoDB",
                27018: "MongoDB-Shard",
                50000: "SAP",
                }


patterns = [
            (re.compile(r"SSH-2\.0-OpenSSH"),              "SSH (OpenSSH)"),
            (re.compile(r"SSH-1\.99"),                     "SSH (compat 1.99)"),
            (re.compile(r"SSH-2\.0-dropbear"),             "SSH (Dropbear)"),
            (re.compile(r"SSH-2\.0-libssh"),               "SSH (libssh)"),

            (re.compile(r"220.*ProFTPD"),                  "FTP (ProFTPD)"),
            (re.compile(r"220.*vsFTPd"),                    "FTP (vsftpd)"),
            (re.compile(r"220.*FileZilla"),                 "FTP (FileZilla)"),
            (re.compile(r"220.*Pure-?FTPd"),                "FTP (Pure-FTPd)"),
            (re.compile(r"220.*Microsoft FTP"),             "FTP (Microsoft IIS)"),

            (re.compile(r"220.*Postfix"),                   "SMTP (Postfix)"),
            (re.compile(r"220.*Exim"),                      "SMTP (Exim)"),
            (re.compile(r"220.*Sendmail"),                  "SMTP (Sendmail)"),
            (re.compile(r"220.*Microsoft ESMTP"),           "SMTP (Exchange)"),

            (re.compile(r"\+OK.*Dovecot"),                  "POP3 (Dovecot)"),
            (re.compile(r"\* OK.*Dovecot"),                 "IMAP (Dovecot)"),
            (re.compile(r"\* OK.*Courier"),                 "IMAP (Courier)"),

            (re.compile(r"^nginx", re.I),          "nginx"),
            (re.compile(r"^Apache", re.I),         "Apache"),
            (re.compile(r"^Microsoft-IIS", re.I),  "IIS"),
            (re.compile(r"^LiteSpeed", re.I),      "LiteSpeed"),
            (re.compile(r"^Caddy", re.I),          "Caddy"),
            (re.compile(r"^gunicorn", re.I),       "Gunicorn (Python)"),
            (re.compile(r"^Werkzeug", re.I),       "Flask Dev Server"),
            (re.compile(r"^cloudflare", re.I),     "Cloudflare"),
            (re.compile(r"^openresty", re.I),      "OpenResty"),
            (re.compile(r"^Jetty", re.I),          "Jetty"),
            (re.compile(r"^Tomcat", re.I),         "Apache Tomcat"),
            (re.compile(r"^Kestrel", re.I),        "Kestrel (.NET)"),
            (re.compile(r"^Node", re.I),           "Node.js"),
            (re.compile(r"^gws", re.I),            "Google Web Server (gws)"),
            (re.compile(r"^ESF", re.I),            "Google ESF"),
            (re.compile(r"^GSE", re.I),            "Google Servlet Engine"),

            (re.compile(r"^HTTP/2(\.0)?$"),          "HTTP/2"),
            (re.compile(r"^HTTP/1\.1$"),             "HTTP/1.1"),
            (re.compile(r"^HTTP/1\.0$"),             "HTTP/1.0"),
            (re.compile(r"^HTTP/0\.9$"),             "HTTP/0.9"),
            (re.compile(r"^h2$"),                    "HTTP/2 (via ALPN)"),
            (re.compile(r"^h2c$"),                   "HTTP/2 cleartext (via ALPN)"),
            (re.compile(r"^http/1\.1$", re.I),       "HTTP/1.1 (via ALPN)"),
            (re.compile(r"^http/1\.0$", re.I),       "HTTP/1.0 (via ALPN)"),

            (re.compile(r"CN=.*\.cloudflare", re.I),        "Cloudflare (via cert)"),
            (re.compile(r"CN=.*\.amazonaws", re.I),         "AWS (via cert)"),
            (re.compile(r"CN=.*\.google", re.I),            "Google (via cert)"),
            (re.compile(r"O=Let's Encrypt", re.I),          "Let's Encrypt cert"),

            (re.compile(r"mysql_native_password"),          "MySQL"),
            (re.compile(r"^.\x00\x00\x00\x0a", re.S),       "MySQL (handshake)"),
            (re.compile(r"PostgreSQL"),                     "PostgreSQL"),
            (re.compile(r"REDIS"),                          "Redis"),
            (re.compile(r"-ERR unknown command"),           "Redis"),
            (re.compile(r"MongoDB"),                        "MongoDB"),

            (re.compile(r"squid", re.I),                    "Squid Proxy"),
            (re.compile(r"Via:\s*.*varnish", re.I),         "Varnish Cache"),

            (re.compile(r"RFB 00"),                          "VNC"),
            (re.compile(r"Microsoft Terminal Services"),     "RDP"),

            (re.compile(r"AMQP"),                           "RabbitMQ/AMQP"),
            (re.compile(r"zookeeper", re.I),                "ZooKeeper"),
            (re.compile(r"kafka", re.I),                    "Kafka"),
            (re.compile(r"elasticsearch", re.I),            "Elasticsearch"),
            (re.compile(r"couchdb", re.I),                  "CouchDB"),
            (re.compile(r"InfluxDB", re.I),                 "InfluxDB"),

            (re.compile(r"OpenVPN"),                        "OpenVPN"),
            (re.compile(r"telnetd", re.I),                  "Telnet"),
            (re.compile(r"NetBIOS"),                        "NetBIOS/SMB"),
            ]